repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        entry: bandit
        args: [ -lll, --recursive, . ]
        language: system
        files: ''
        name: bandit

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
        language: system